### ISSUE TITLE
Combo Points and Combo Type don't appear when comparing two characters

### ISSUE THREAD

**Issue by hobusu** [cpennington/yomibase#15]
This was probably intentional, but the column that shows the Combo Type and Combo Points for moves disappears when two characters are being compared, seemingly to make space for the column that says who a move belongs to. The name column seems redundant now that the character-specific background colors and player-specific border colors are implemented, whereas the combo column is relevant at all times.

**Comment by cpennington** [comment]
I think having a name column is still potentially useful to sort the set of moves by the character. But I might shrink it in size to just have a mini headshot (but still sort alphabetically).

**Comment by hobusu** [comment]
That sounds reasonable. Just so long as I can see the combo details for a move when comparing characters, I'm happy!
