### ISSUE TITLE
Edit link at bottom of EX Grave's page doesn't show Grave's name

### ISSUE THREAD

**Issue by hobusu** [cpennington/yomibase#17]
I'll admit that it was amusing to see "Found a bug, or have a suggestion about ? Suggest a change here." That said, it should be a simple enough fix.

**Comment by hobusu** [comment]
As expected, this also applies to the other variants.

**Comment by hobusu** [comment]
What I didn't expect is that it would also apply to the base characters, regardless of whether they have variants...

**Comment by cpennington** [comment]
Should be fixed shortly.
