### ISSUE TITLE
Unable to select multiple EX Characters

### ISSUE THREAD

**Issue by hobusu** [cpennington/yomibase#18]
When I select two different characters that have EX versions added, switching one of them to EX mode prevents me from switching the other to EX mode. The option is greyed out for the character that hasn't been switched.

**Comment by hobusu** [comment]
Further testing has revealed that this issue only applies to Player 2, and it's actually that Player 2 can't select the same variant type as Player 1. What I mean is that if Player 1 has selected EX Grave, Player 2 can't switch from normal Jaina to EX Jaina, but if Player 1 has selected normal Grave and Player 2 is already on EX Jaina, Player 2 can't switch back to normal Jaina.

**Comment by cpennington** [comment]
Ah, yes, I know exactly why that is... This is what I get for re-using the same selectors for EX mode that I used for mobile character select. Time to refactor.
