### ISSUE TITLE
EX Valerie only shows 6 combo points despite having 8

### ISSUE THREAD

**Issue by hobusu** [cpennington/yomibase#20]
This seems to be a result of the way combo points are displayed, since the max with your current format is 6 points. It would be nice if all the combo information could also display enough empty dots to make it clear that there's a max of 8 points, but that comes after getting the maximum to display at all for the character summary.

**Comment by cpennington** [comment]
Sweet. I totally didn't consider the possibility of a character having 8 combo points.
