### ISSUE TITLE
Selecting Persephone causes crash/blank page

### ISSUE THREAD

**Issue by hobusu** [cpennington/yomibase#33]
Any time I try to select Persephone, the page immediately goes completely blank and any ability to interact with the site disappears. It doesn't matter which side of the matchup Persephone is selected for, whether any other characters have been selected or not, nor whether EX has been enabled for any characters or not. Refreshing doesn't fix it, but using the Back button (so Persephone isn't selected) and _then_ refreshing does make things return to normal.

Confirmed on both my Asus Chromebook and my Moto G Android phone, both using Google Chrome.

**Comment by hobusu** [comment]
Don't have time to confirm on my PC, but I'm 99% sure it'll be there too if it was on both of my other devices. I can confirm that this only seems to affect Persephone, not any other characters.

**Comment by cpennington** [comment]
Ok, I'll check it out. And add more tests.

**Comment by hobusu** [comment]
Just confirmed that it also happens on my PC, using Chrome of course. I can give more specs on any of them if you'd like, but since it happens on three disparate machines I doubt the specifics matter much beyond "I was using Chrome for all three of them."

**Comment by cpennington** [comment]
I know what the big is. Just need to sit down and write the fix.

Thanks for catching it!

**Comment by cpennington** [comment]
Ok, this should be fixed shortly.
